name: Build Filebrowser

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'   # Use Node 22 to match package.json requirement

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install frontend and build
        run: |
          cd frontend
          pnpm install
          pnpm run build
          cd ..

      - name: Build backend
        run: |
          go build -o filebrowser

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: filebrowser
          path: ./filebrowser
